language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt551 -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install python-pip
  - pip install --user cpp-coveralls

install:
  - sudo apt-get install -qq g++-5
  - sudo apt-get install qt55base
  - sudo apt-get install qt55multimedia
  - sudo apt-get install cppcheck

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3


script:
  - source /opt/qt55/bin/qt55-env.sh
  - g++-5 --version
  - qmake --version
  - qmake "QMAKE_CXX=g++-5" "CC=gcc-5" "CONFIG+=travis" CoBaB.pro
  - make
  - ls -la
  - cd test
  - ./test
  - cd ..
  - cppcheck . -q --error-exitcode=31
  - ./configure --enable-gcov && make && makecheck

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
